package rules.templates;
import game.helper.model.*;
import game.helper.model.enums.*;
import game.helper.model.dto.*;
import java.util.ArrayList;
import java.util.List;

rule "User similarity"
	agenda-group "users"
	lock-on-active
	salience 10
    when    
        $umDTO: UserMatchDTO($u: user, $reviews: reviews, $user_reviews: user.reviews)
        $r: Review($game: game) from $reviews
        $match: Review(game == $game) from $user_reviews     
    then
    	$umDTO.setNo_matches($umDTO.getNo_matches() + 1);
        update($umDTO);
end
rule "User similarity categorisation - LOW"
	agenda-group "users"
	
	salience 5
    when    
        $umDTO: UserMatchDTO(no_matches >= 1 && no_matches < 2)
    then
    	$umDTO.setMatchCoeficient(MatchCoeficient.USER_LOW_MATCH);
        update($umDTO);
end
rule "User similarity categorisation - MID"
	agenda-group "users"
	
	salience 5
    when    
        $umDTO: UserMatchDTO(no_matches >= 2 && no_matches < 5)
    then
       	$umDTO.setMatchCoeficient(MatchCoeficient.USER_MID_MATCH);
        update($umDTO);
end
rule "User similarity categorisation - HIGH"
	agenda-group "users"
	
	salience 5
    when    
        $umDTO: UserMatchDTO(no_matches >= 5)
    then
    	$umDTO.setMatchCoeficient(MatchCoeficient.USER_HIGH_MATCH);
        update($umDTO);
end


